platform :ios, '12.0'

target 'Flat' do
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  
  pod 'DifferenceKit'
  pod 'SwiftTrace'
  pod 'Kingfisher'
  pod 'Hero'
  pod 'SnapKit'
  pod 'EmptyDataSet-Swift'
  pod 'IQKeyboardManagerSwift'
  
  pod 'Whiteboard'
  pod 'WechatOpenSDK'
  pod 'AgoraRtm_iOS'
  pod 'AgoraRtcEngine_iOS'
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
